### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected

### ISSUE THREAD

**Issue by yesidlazaro** [realm/realm-android-adapters#101]
Hi , i am having this weird issue , i am saving some realm objects and the adapter(subclass of RealmRecyclerViewAdapter) display them correctly but sometimes the app crash with the log. i saving the objects with this method: 
```java
            realm.beginTransaction();
            realm.copyToRealm(newChat);
            realm.commitTransaction();
```
#### stack trace

```java
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{638af31 position=3 id=-1, oldPos=2, pLpos:2 scrap [attachedScrap] tmpDetached not recyclable(1) no parent}
       at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5297)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5479)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
       at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1648)
       at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:343)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:618)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6126)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

#### Version of Realm and tooling
Realm version(s): 3.0.0

Android Studio version:2.3 stable

Which Android version and device: nexus 5 with android 7.1.1

**Comment by dalinaum** [comment]
Hello @yesidlazaro I cannot find clues from this stack trace. Can you share your code to help@realm.io?

**Comment by binpower93** [comment]
I also have this issue, running the latest version of Realm. https://fabric.io/ben-barber/android/apps/com.github.binpower93.stationhubapp/issues/58d357fd0aeb16625bbb01a6

**Comment by cmelchior** [comment]
This should be fixed in `3.1-SNAPSHOT` by https://github.com/realm/realm-java/pull/4368

**Comment by yesidlazaro** [comment]
@cmelchior thanks, i going to test today.

**Comment by johnryan** [comment]
@yesidlazaro Did this fix your issue? i'm seeing the same problem

**Comment by Quarx2k** [comment]
Yes, problem still exist. 
'io.realm:realm-gradle-plugin:3.1.2'
compile 'io.realm:android-adapters:2.0.0'

It's known bug of last versions of support lib;
http://stackoverflow.com/questions/31759171/recyclerview-and-java-lang-indexoutofboundsexception-inconsistency-detected-in/33822747#33822747

**Comment by kneth** [comment]
It sounds like the issue has been solved.
